flowchart TD
    User[User] -->|Login Request| API[API Endpoint /auth/login]
    API --> Auth[Auth Middleware]
    Auth --> UserController[User Controller]
    UserController --> UserModel[User Model]
    UserModel --> DB[(MongoDB)]
    API -->|JWT Token| User

    User -->|Authenticated API Request| API2[API Endpoint ]
    API2 --> Auth2[Auth Middleware]
    Auth2 --> Controller[Business Controller]
    Controller --> Model[Mongoose Model]
    Model --> DB
    Controller -->|On Delete| UniversalBackup[UniversalBackup Model]
    UniversalBackup --> DB

    User -->|Create Ticket| API_Ticket[API /tickets]
    API_Ticket --> Auth_Ticket[Auth Middleware]
    Auth_Ticket --> TicketController[Ticket Controller]
    TicketController --> TicketModel[Ticket Model]
    TicketModel --> DB

    User -->|Log Time| API_LogTime[API /logtime]
    API_LogTime --> Auth_LogTime[Auth Middleware]
    Auth_LogTime --> LogTimeController[LogTime Controller]
    LogTimeController --> LogTimeModel[LogTime Model]
    LogTimeModel --> DB

    User -->|CRUD Items/Clients/Suppliers| API_Other[API Endpoint]
    API_Other --> Auth_Other[Auth Middleware]
    Auth_Other --> OtherController[Other Controllers]
    OtherController --> OtherModel[Other Models]
    OtherModel --> DB
